### ISSUE TITLE
Support JWT auth method

### ISSUE THREAD

**Issue by razor-x** [seamapi/fake-seam-connect#124]
See also https://github.com/seamapi/nextlove/pull/124 and https://github.com/seamapi/fake-seam-connect/issues/126

**Comment by andrii-balitskyi** [comment]
@razor-x could you give me more details on this one? For example, `console_session` auth uses `withSessionAuth` middleware which does [decode](https://github.com/seamapi/fake-seam-connect/blob/2a7cf09b90117011114318275f855ff9a056d8ac/src/lib/middleware/with-session-auth.ts#L59) JWT tokens. Is this issue about creating a new auth middleware?

**Comment by razor-x** [comment]
`fake-seam-connect` should support a subset of the of the auth middle ware supported by seam connect. https://github.com/seamapi/fake-seam-connect/blob/main/src/lib/middleware/with-route-spec.ts#L19-L45

This issue is really referring to the `console_session` auth method (which uses JWT).
