### ISSUE TITLE
Support personal access tokens

### ISSUE THREAD

**Issue by razor-x** [seamapi/fake-seam-connect#126]
See also https://github.com/seamapi/nextlove/pull/124 and https://github.com/seamapi/fake-seam-connect/issues/124

**Comment by andrii-balitskyi** [comment]
@razor-x we have [`withAccessToken`](https://github.com/seamapi/fake-seam-connect/blob/main/src/lib/middleware/with-access-token.ts) middleware. The fake also supports `pat_with_workspace` and `pat_without_workspace` [[source](https://github.com/seamapi/fake-seam-connect/blob/2a7cf09b90117011114318275f855ff9a056d8ac/src/lib/middleware/with-route-spec.ts#L50-L51)]. 
What else this issue requires to be implemented?

**Comment by razor-x** [comment]
@andrii-balitskyi Yea, the auth methods were added but were not working. Getting these tests to pass is the first step in verifying those auth methods work https://github.com/seamapi/javascript-http/pull/150/files#diff-8f55516b1f0506eb134563710a3c6be8690e5f149de0810491a634f536fbcd4c
