### ISSUE TITLE
Emulate fake visionline and assa abloy on fake seam-connect

### ISSUE THREAD

**Issue by ethanplee14** [seamapi/fake-seam-connect#136]
In order to test the mobile sdk, we need to be able to register an endpoint from fake visionline and simulate reader behaviors. Since we're using fake seam connect, it doesn't hold any references to underlying fakes (double fake problem). In order to get around this we need to implement `fake visionline` endpoints into `fake seam connect`. We need everything under the `api/_fake` endpoints: 

- [ ] api/_fake/load_credentials
- [x] api/_fake/redeem_invite_code
- [ ] api/simulate/readers/list
- [ ] api/simulate/readers/unlock

We need it in reference to this section of the sequence diagram: 
![Image](https://github.com/seamapi/fake-seam-connect/assets/18000293/48ea384a-2f08-44e3-b0b0-eaa40822a825)

**Comment by codetheweb** [comment]
In other cases where we have nested fakes we have the user handle the lifecycle of all `@seamapi/fake-*` servers and pass base URLs to other fakes to the entrypoint fake as necessary. Is that possible here?

**Comment by ethanplee14** [comment]
> In other cases where we have nested fakes we have the user handle the lifecycle of all @seamapi/fake-* servers and pass base URLs to other fakes to the entrypoint fake as necessary. Is that possible here?

We will still have to facilitate fake-seam-connect updates correct? So for example if i create an access code on fake schlage, i'll have to update fake-seam-connect with the new access code?

**Comment by ethanplee14** [comment]
@seveibar and I talked about this and we were discussing a parallel fake approach vs faking the fake, and we thought the orchestration would be a bit difficult and the question of who owns that orchestration is also weird. 

We figured fakes are useful for simulating behavior already so orchestration should also live there, hence emulating fake visionline and assa abloy in here. But i have no experience in this so if you think otherwise @codetheweb

**Comment by seveibar** [comment]
@codetheweb doesnt work easily with the superfake servers, if the emulation of the 2nd layer gets bad i think we should consider it doing fake DI as youre suggesting (superfakes could infer the base url of visionline using their own base url) but the dip into visionline is so minor im not sure its worth it for now

**Comment by seveibar** [comment]
Another point is this repo is public but visionline is publicly available, so a bit of emulation is probably ok bit we have to be a bit cautious in our approach, testing in this repo is nontrivial without using fake visionlines source

**Comment by codetheweb** [comment]
> Another point is this repo is public but visionline is publicly available, so a bit of emulation is probably ok bit we have to be a bit cautious in our approach, testing in this repo is nontrivial without using fake visionlines source

ah yeah good point

**Comment by ethanplee14** [comment]
Looks like ravi completed the `fake/redeem_invite_code`
