### ISSUE TITLE
Publish workflow is failing

### ISSUE THREAD

**Issue by razor-x** [seamapi/fake-seam-connect#224]
See https://github.com/seamapi/fake-seam-connect/actions/runs/11956748436/job/33332236969

Why is `npm ci` only failing on publish and not the other checks?

**Comment by razor-x** [comment]
Related to https://github.com/seamapi/seam-cli/issues/260

**Comment by andrii-balitskyi** [comment]
Not sure what fixed it but looks like publish workflow is working again https://github.com/seamapi/fake-seam-connect/actions/runs/12200535543/job/34036893159
