### ISSUE TITLE
Add /_fake/seed

### ISSUE THREAD

**Issue by razor-x** [seamapi/fake-seam-connect#44]
[Returns the seed object](https://github.com/seamapi/fake-seam-connect/blob/8dabead4a24071be9758e06d855879a23e972974/src/lib/database/seed.ts#L99) if the db is seeded, otherwise returns `null` (or status code?)

**Comment by seveibar** [comment]
Interesting idea, this is a bit easier than parsing the database. I think I'm generally in agreement this would be handy
